import 'package:flutter/material.dart';

class S {
  final Locale locale;

  S(this.locale);

  static S of(BuildContext context) {
    return Localizations.of<S>(context, S) ?? S(const Locale('vi'));
  }

  String get languageCode => locale.languageCode;

  // Translations
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // General
      'cancel': 'Cancel',
      'save': 'Save',
      'edit': 'Edit',
      'delete': 'Delete',
      'amount': 'Amount',
      'note': 'Note',
      'enter_note': 'Enter note',
      'unit': 'Currency',
      'options': 'Options',
      'dark_mode': 'Dark Mode',
      'support': 'Support',
      'login': 'Login',
      'logout': 'Logout',
      'working_hours': 'Working hours: 8am - 5pm',
      'share_app': 'Share App',
      'share_message': 'Managing your finances is easier with OneMoreCoin! Download now to experience it.',
      
      // Home
      'total_balance': 'Total Balance',
      'income': 'Income',
      'expense': 'Expense',
      'recent_transactions': 'Recent Transactions',
      'my_wallet': 'My Wallet',
      'view_all': 'View All',
      'spending_report': 'Spending Report',
      'no_transactions_yet': 'No transactions yet',
      'all_wallets': 'All Wallets',
      'details': 'Details',
      'results': 'results',
      'budget': 'Budget',
      'currently': 'Currently',
      'total_spent_this_week': 'Total spent this week',
      'total_spent_this_month': 'Total spent this month',
      'most_spent_group_in_week': 'Most spent group in week',
      'most_spent_group_in_month': 'Most spent group in month',
      'most_spent_group_empty': 'The group with the most spending will be displayed here!',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'month_label': 'month',
      'hours': 'hours',
      'days': 'days',
      'main_wallet': 'Main Wallet',
      'select_date': 'Select Date',
      'choose_from_gallery': 'Choose from gallery',
      'take_photo': 'Take a photo',
      'remove_avatar': 'Remove avatar',
      'quick_stats': 'Quick Stats',
      'quick_add': 'Quick Add',
      'food': 'Food & Drink',
      'coffee': 'Coffee',
      'transport': 'Transport',
      'add_widget': 'Add Widget',
      'period_report': 'Period Report',
      'spending_in_period': 'Total Spent',
      'lending': 'Lending',
      'borrowing': 'Borrowing',
      'hide_stats': 'Hide',
      'show_stats': 'Show',
      
      // Transactions
      'today': 'Today',
      'yesterday': 'Yesterday',
      'day_before_yesterday': 'Day before yesterday',
      'custom': 'Custom',
      'please_select_group': 'Please select a group',
      'please_select_wallet': 'Please select a wallet',
      'please_enter_amount': 'Please enter amount',
      'amount_greater_than_0': 'Amount must be greater than 0',
      'add_details': 'Add details',
      'exclude_from_report': 'Exclude from report',
      'create_transaction': 'Create transaction',
      'time_period': 'Time period',
      'transaction_book': 'Transaction Book',
      'confirm_delete_transaction': 'Confirm delete this transaction?',
      'confirm_delete_budget': 'Confirm delete this budget?',
      'actual_spending': 'Actual spending',
      'expected': 'Expected',
      'overspending': 'Overspending',
      'budget_auto_repeat_next_period': 'Budget will automatically repeat in the next period',
      'spent_today_label': 'Spent Today',
      'spent_today': 'Spent today',
      'used_percent': 'Used ',
      'standard_daily_spending': 'Standard daily spending',
      'actual_daily_spending': 'Actual daily spending',
      'expected_daily_spending': 'Expected daily spending',
      'transaction_list': 'Transaction list',
      'overview': 'Overview',
      'today_overview': 'Today\'s Overview',
      'transactions': 'Transactions',
      'account': 'Account',
      'day': 'Day',
      'week': 'Week',
      'month': 'Month',
      'quarter': 'Quarter',
      'year': 'Year',
      'all': 'All',
      'view_by_group': 'View by group',
      'view_by_date': 'View by date',
      'transaction_count': 'transactions',
      'no_transactions': 'No transactions',
      'opening_balance': 'Opening balance',
      'ending_balance': 'Ending balance',
      'view_report_for_period': 'View report for this period',
      'day_before_yesterday_caps': 'DAY BEFORE YESTERDAY',
      'yesterday_caps': 'YESTERDAY',
      'today_caps': 'TODAY',
      'last_week_caps': 'LAST WEEK',
      'this_week_caps': 'THIS WEEK',
      'last_month_caps': 'LAST MONTH',
      'this_month_caps': 'THIS MONTH',
      'last_year_caps': 'LAST YEAR',
      'this_year_caps': 'THIS YEAR',
      'future_caps': 'FUTURE',
      'all_transactions_caps': 'ALL TRANSACTIONS',
      'balance': 'Balance',
      'add_transaction': 'Add Transaction',
      'edit_transaction': 'Edit Transaction',
      'select_group': 'Select Group',
      'select_wallet': 'Select Wallet',
      'add_to_report': 'Include in report',
      'add_wallet': 'Add Wallet',
      'wallet_name': 'Wallet Name',
      'please_enter_wallet_name': 'Please enter wallet name',
      'please_enter_balance': 'Please enter balance',
      'invalid_balance': 'Invalid balance',
      'initial_balance': 'Initial balance',
      'include_in_report': 'Include in report',
      'create_wallet': 'Create Wallet',
      'cannot_delete_main_wallet': 'Cannot delete main wallet',
      'confirm_delete_wallet': 'Are you sure you want to delete wallet ',
      'wallet_delete_warning': 'Transactions in this wallet will be kept, but the wallet name in history will appear as \'Deleted wallet\'.',
      'deleted_wallet_success': 'Deleted wallet ',
      'close': 'Close',
      'add_new_wallet': 'Add new wallet',
      'new_group': 'New Group',
      'group_name': 'Group Name',
      'expense_item': 'Expense',
      'income_item': 'Income',
      'create_group': 'Create Group',
      'group_list': 'Group List',
      
      // Budgets
      'budgets': 'Budgets',
      'add_budget': 'Add Budget',
      'edit_budget': 'Edit Budget',
      'remaining': 'Remaining',
      'spent': 'Spent',
      'no_budgets': 'You have no budgets',
      'budget_prompt_desc': 'Start saving by creating a budget and we will help you control your spending',
      'create_budget': 'CREATE BUDGET',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'this_quarter': 'This Quarter',
      'this_year': 'This Year',
      'please_enter_budget_amount': 'Please enter budget amount',
      'repeat_periodically': 'Repeat periodically',
      'create_budget_btn': 'Create budget',
      'no_finished_budgets': 'No finished budgets',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'this_period': 'this',
      'remaining_colon': 'Remaining:',
      'overspent_colon': 'Overspent:',
      'in_progress': 'IN PROGRESS',
      'finished': 'FINISHED',
      
      // Profile
      'login_prompt': 'Please login to manage your account',
      'delete_all_data': 'Delete all data',
      'create_test_data': 'Create test data',
      'set_reminder': 'Set reminder',
      'date': 'Date',
      'time': 'Time',
      
      // Auth
      'welcome_back': 'Welcome Back!',
      'login_to_manage': 'Log in to manage your spending',
      'username_or_email': 'Username or Email',
      'please_enter_username_or_email': 'Please enter username or email',
      'password': 'Password',
      'please_enter_password': 'Please enter password',
      'skip_login': 'Skip login',
      'no_account': 'Don\'t have an account? ',
      'register_now': 'Register now',
      'password_not_match': 'Passwords do not match',
      'register_success': 'Registration successful! Redirecting to login...',
      'register_account': 'Register Account',
      'create_new_account': 'Create New Account',
      'fill_info_to_register': 'Fill in the information below to register',
      'display_name': 'Display Name',
      'please_enter_display_name': 'Please enter display name',
      'email': 'Email',
      'please_enter_email': 'Please enter email',
      'invalid_email': 'Invalid email',
      'username': 'Username',
      'please_enter_username': 'Please enter username',
      'username_min_length': 'Username must be at least 3 characters',
      'password_min_length': 'Password must be at least 6 characters',
      'confirm_password': 'Confirm password',
      'please_confirm_password': 'Please confirm password',
      'register': 'Register',
      'already_have_account': 'Already have an account? ',
      
      // Export & Backup
      'export_backup': 'Export & Backup',
      'export_data': 'Export Data',
      'export_excel': 'Export Excel (.xlsx)',
      'export_pdf': 'Export PDF',
      'export_csv': 'Export CSV',
      'backup_data': 'Backup Data',
      'restore_data': 'Restore Data',
      'backup_section': 'Backup',
      'restore_confirm': 'Current data will be replaced. Are you sure?',
      'restore_success': 'Data restored successfully',
      'restore_fail': 'Restore failed',
      'export_success': 'Export successful',
      'export_fail': 'Export failed',
      'backup_success': 'Backup successful',
      'no_transactions_to_export': 'No transactions to export',
      'transaction_report': 'Transaction Report',
      'export_date': 'Export Date',
      'total_income': 'Total Income',
      'total_expense': 'Total Expense',
      'serial_number': 'No.',
      'title': 'Title',
      'type': 'Type',
      'group': 'Group',
      'wallet': 'Wallet',
      'export_filter': 'Export Filter',
      'filter_all': 'All',
      'filter_day': 'By day',
      'filter_month': 'By month',
      'filter_quarter': 'By quarter',
      'filter_year': 'By year',
      'filter_range': 'Time range',
      'select_range': 'Select time range',

      // Confirmations
      'confirm_delete': 'Confirm delete?',
      'delete_all_confirm': 'Are you sure you want to delete all data?',
      'edit_wallet': 'Edit Wallet',

      // Security
      'security': 'Security',
      'link_phone': 'Link Phone Number',
      'phone_number': 'Phone Number',
      'pin_code': 'PIN Code',
      'create_pin_code': 'Create PIN',
      'change_pin_code': 'Change PIN',
      'enter_pin': 'Enter PIN',
      'pin_created': 'PIN created successfully',
      'pin_changed': 'PIN changed successfully',
      'pin_removed': 'PIN removed successfully',
      'incorrect_pin': 'Incorrect PIN',
      'change_password': 'Change Password',
      'old_password': 'Old Password',
      'new_password': 'New Password',
      'password_changed': 'Password changed successfully',
      'remove_pin': 'Remove PIN',
      'please_enter_phone': 'Please enter phone number',
      'phone_linked': 'Phone number linked',
      'remove_phone': 'Remove Phone Number',
      'phone_removed': 'Phone number removed',
      'incorrect_old_password': 'Incorrect old password',
      'pin_required_desc': 'You need to create a PIN code to perform this action. Do you want to create one now?',
      'create_pin_now': 'Create PIN Now',

      // ChatBot
      'chatbot_welcome': 'Hello! 👋 Let\'s start adding your transactions here!',
      'chatbot_hint': 'dinner 100k, shopping 400k',
      'chatbot_success_expense': 'Great! I\'ve recorded your expense in the {group} category. Keep up the good habit! 💪',
      'chatbot_success_income': 'Great! I\'ve recorded your income in the {group} category. Keep up the good habit! 💪',
      'chatbot_error_parse': 'Sorry, an error occurred during analysis. Please try again.',
      'chatbot_error_understand': 'I haven\'t quite understood yet, could you be more specific? (e.g. \"Coffee 50k this morning\")',
      'chatbot_title': 'What did you spend today?',
      'chatbot': 'Financial Assistant',
      'chatbot_subtitle': 'AI Assistant',
      'chatbot_spending': 'Spending',
      'chatbot_no_transaction': 'No transactions in this period 📭',
      'chatbot_summary': '📊 Summary: {count} transactions\n',
      'chatbot_total_expense': '💸 Expense: {amount}\n',
      'chatbot_total_income': '💰 Income: {amount}',
      'chatbot_recorded': 'Recorded: ',
      'chatbot_expense_label': 'Expense',
      'chatbot_income_label': 'Income',
      'chatbot_transfer_fund': 'Transfer funds',
      'chatbot_recurring': 'Recurring transaction',

      // Reminders
      'payment_reminders': 'Payment Reminders',
      'no_reminders_yet': 'No reminders yet.',
      'add_reminder': 'Add Reminder',
      'edit_reminder': 'Edit Reminder',
      'reminder_title_hint': 'Title (e.g. March Electricity)',
      'bill_type': 'Bill Type',
      'expected_amount': 'Expected Amount',
      'due_date_label': 'Due Date',
      'remind_before_days': 'Remind before (days)',
      'notification_time': 'Notification time (default 08:00)',
      'additional_notes': 'Additional notes',
      'save_reminder': 'Save Reminder',
      'type_electricity': 'Electricity',
      'type_water': 'Water',
      'type_internet': 'Internet',
      'type_rent': 'Rent',
      'type_other': 'Other',
      'mark_as_paid': 'Mark as paid',
      'delete_reminder': 'Delete reminder',
      'x_days': 'days',
      'tomorrow': 'Tomorrow',
      'reminder_hint': 'Tap + to add a new reminder',
      'search_reminder': 'Search reminders...',
      'scan_receipt_tip': 'Tip: Tap to scan receipt for quick entry',
      'sort_newest': 'Newest',
      'sort_due_soon': 'Due soon',
      'no_results_found': 'No results found',
      'enter_title': 'Please enter a title',
      'enter_amount': 'Please enter an amount',
      
      // OCR & Scanning
      'scan_receipt': 'Scan Receipt',
      'select_receipt_image': 'Select receipt image',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'scanning_receipt': 'Analyzing receipt...',
      'scan_result': 'Scan Result',
      'category': 'Category',
      'items': 'Items',
      'use_result': 'Use this result',

      // Loan Management
      'loan_management': 'Loan Management',
      'loan_subtitle': 'Borrow & Lend',
      'loan_borrow': 'Borrow',
      'loan_lend': 'Lend',
      'total_borrowed': 'Total Borrowed',
      'total_lent': 'Total Lent',
      'loan_items': 'loans',
      'search_person': 'Search by person...',
      'loan_unpaid': 'Unpaid',
      'loan_partial': 'Partial Paid',
      'loan_paid': 'Paid',
      'no_loans': 'No loans yet',
      'loan_paid_amount': 'Paid',
      'loan_remaining': 'Remaining',
      'loan_overdue': 'Overdue!',
      'add_loan': 'Add Loan',
      'edit_loan': 'Edit Loan',
      'loan_borrower': 'Borrower',
      'loan_creditor': 'Creditor',
      'please_enter_person': 'Please enter person name',
      'loan_date': 'Date',
      'loan_due_date': 'Due Date',
      'not_set': 'Not set',
      'loan_detail': 'Loan Detail',
      'status': 'Status',
      'loan_payment_history': 'Payment History',
      'loan_add_payment': 'Add Payment',
      'no_payments': 'No payment history',
      'confirm_delete_loan': 'Are you sure you want to delete this loan?',
      'confirm_delete_payment': 'Delete this payment?',
      'loan_borrow_hint': 'Tap + to add a new loan',
      'loan_lend_hint': 'Tap + to add a new lending',

      // Categories
      'sub_category': 'Sub-category',
      'edit_group': 'Edit Category',
      'category_type': 'Category Type',
      'category_color': 'Color',
      'parent_category': 'Parent Category',
      'no_parent': 'None (Root Category)',
      'please_fill_all': 'Please fill all fields',
      'confirm_delete_group': 'Are you sure you want to delete this category? Transactions using this category will not be deleted.',
      'version': 'Version',

      // Notifications
      'notifications': 'Notifications',
      'mark_all_read': 'Mark all as read',
      'unread': 'Unread',
      'bill': 'Bill',
      'debt': 'Debt',
      'no_notifications': 'No notifications',
      'reminder_payment_title': 'Bill Payment Reminder',
      'reminder_payment_body': 'Bill payment due: {0} for {1}',
      'debt_due_title': 'Debt Due',
      'debt_payment_body': 'You need to pay {0} to {1}',
      'loan_due_title': 'Loan Collection Due',
      'loan_collection_body': 'Collection due: {0} from {1}',
      'loan_created_borrow': 'Loan Created',
      'loan_created_borrow_body': 'You borrowed {0} from {1}',
      'loan_created_lend': 'Lending Created',
      'loan_created_lend_body': 'You lent {0} to {1}',
    },
    'vi': {
      // General
      'cancel': 'Huỷ',
      'save': 'Lưu',
      'edit': 'Sửa',
      'delete': 'Xoá',
      'amount': 'Số tiền',
      'note': 'Ghi chú',
      'enter_note': 'Nhập ghi chú',
      'unit': 'Đơn vị tiền tệ',
      'options': 'Tuỳ chọn',
      'dark_mode': 'Chế độ tối',
      'support': 'Hỗ trợ',
      'login': 'Đăng nhập',
      'logout': 'Đăng xuất',
      'working_hours': 'Thời gian làm việc từ : 8h - 17h',
      'share_app': 'Chia sẻ ứng dụng',
      'share_message': 'Quản lý tài chính dễ dàng hơn cùng OneMoreCoin! Tải ngay để trải nghiệm nhé.',
      
      // Home
      'total_balance': 'Tổng số dư',
      'income': 'Thu nhập',
      'expense': 'Chi tiêu',
      'recent_transactions': 'Giao dịch gần đây',
      'my_wallet': 'Ví của tôi',
      'view_all': 'Xem tất cả',
      'spending_report': 'Báo cáo chi tiêu',
      'no_transactions_yet': 'Chưa có giao dịch nào',
      'all_wallets': 'Tất cả các ví',
      'details': 'Chi tiết',
      'results': 'kết quả',
      'budget': 'Ngân sách',
      'currently': 'Hiện tại',
      'total_spent_this_week': 'Tổng đã chi tuần này',
      'total_spent_this_month': 'Tổng đã chi tháng này',
      'most_spent_group_in_week': 'Nhóm chi nhiều nhất trong tuần',
      'most_spent_group_in_month': 'Nhóm chi nhiều nhất trong tháng',
      'most_spent_group_empty': 'Nhóm chi tiêu nhiều nhất sẽ được hiển thị ở đây!',
      'monday': 'Thứ hai',
      'tuesday': 'Thứ ba',
      'wednesday': 'Thứ tư',
      'thursday': 'Thứ năm',
      'friday': 'Thứ sáu',
      'saturday': 'Thứ bảy',
      'sunday': 'Chủ nhật',
      'month_label': 'tháng',
      'hours': 'giờ',
      'days': 'ngày',
      'main_wallet': 'Ví chính',
      'select_date': 'Chọn ngày',
      'choose_from_gallery': 'Chọn từ thư viện',
      'take_photo': 'Chụp ảnh',
      'remove_avatar': 'Xóa ảnh đại diện',
      'quick_stats': 'Thống kê nhanh',
      'quick_add': 'Thêm nhanh',
      'food': 'Ăn uống',
      'coffee': 'Cafe',
      'transport': 'Đi lại',
      'add_widget': 'Thêm widget',
      'period_report': 'Báo cáo theo giai đoạn',
      'spending_in_period': 'Chi tiêu trong kỳ',
      'lending': 'Cho vay',
      'borrowing': 'Đi vay',
      'hide_stats': 'Ẩn',
      'show_stats': 'Hiện',
      
      // Transactions
      'today': 'Hôm nay',
      'yesterday': 'Hôm qua',
      'day_before_yesterday': 'Hôm kia',
      'custom': 'Tuỳ chọn',
      'please_select_group': 'Vui lòng chọn nhóm',
      'please_select_wallet': 'Vui lòng chọn ví',
      'please_enter_amount': 'Vui lòng nhập số tiền',
      'amount_greater_than_0': 'Số tiền phải lớn hơn 0',
      'add_details': 'Thêm chi tiết',
      'exclude_from_report': 'Không tính vào báo cáo',
      'create_transaction': 'Tạo giao dịch',
      'time_period': 'Khoảng thời gian',
      'transaction_book': 'Sổ giao dịch',
      'confirm_delete_transaction': 'Xác nhận xoá giao dịch này?',
      'confirm_delete_budget': 'Xác nhận xoá ngân sách này?',
      'actual_spending': 'Chi tiêu thực tế',
      'expected': 'Dự kiến',
      'overspending': 'Bội chi',
      'budget_auto_repeat_next_period': 'Ngân sách được tự động lặp lại ở kỳ tiếp theo',
      'spent_today_label': 'Chi hôm nay',
      'spent_today': 'Chi trong hôm nay',
      'used_percent': 'Đã dùng ',
      'standard_daily_spending': 'Tiêu chuẩn chi tiêu hằng ngày',
      'actual_daily_spending': 'Thực tế chi tiêu hằng ngày',
      'expected_daily_spending': 'Dự kiến chi tiêu hằng ngày',
      'transaction_list': 'Danh sách giao dịch',
      'overview': 'Tổng quan',
      'today_overview': 'Tổng quan hôm nay',
      'transactions': 'Giao dịch',
      'account': 'Tài khoản',
      'day': 'Ngày',
      'week': 'Tuần',
      'month': 'Tháng',
      'quarter': 'Quý',
      'year': 'Năm',
      'all': 'Tất cả',
      'view_by_group': 'Xem theo nhóm',
      'view_by_date': 'Xem theo ngày giao dịch',
      'transaction_count': 'giao dịch',
      'no_transactions': 'Không có giao dịch nào',
      'opening_balance': 'Số dư đầu kỳ',
      'ending_balance': 'Số dư cuối kỳ',
      'view_report_for_period': 'Xem báo cáo cho giai đoạn này',
      'day_before_yesterday_caps': 'HÔM KIA',
      'yesterday_caps': 'HÔM QUA',
      'today_caps': 'HÔM NAY',
      'last_week_caps': 'TUẦN TRƯỚC',
      'this_week_caps': 'TUẦN NÀY',
      'last_month_caps': 'THÁNG TRƯỚC',
      'this_month_caps': 'THÁNG NÀY',
      'last_year_caps': 'NĂM TRƯỚC',
      'this_year_caps': 'NĂM NÀY',
      'future_caps': 'TƯƠNG LAI',
      'all_transactions_caps': 'TẤT CẢ GIAO DỊCH',
      'balance': 'Số dư',
      'add_transaction': 'Thêm giao dịch',
      'edit_transaction': 'Sửa giao dịch',
      'select_group': 'Chọn nhóm',
      'select_wallet': 'Chọn ví',
      'add_to_report': 'Thêm vào báo cáo',
      'add_wallet': 'Thêm ví',
      'wallet_name': 'Tên ví',
      'please_enter_wallet_name': 'Vui lòng nhập tên ví',
      'please_enter_balance': 'Vui lòng nhập số dư',
      'invalid_balance': 'Số dư không hợp lệ',
      'initial_balance': 'Số dư ban đầu',
      'include_in_report': 'Tính vào báo cáo',
      'create_wallet': 'Tạo ví',
      'cannot_delete_main_wallet': 'Không thể xoá ví chính',
      'confirm_delete_wallet': 'Bạn có chắc chắn muốn xoá ví ',
      'wallet_delete_warning': 'Các giao dịch thuộc ví này vẫn sẽ được giữ lại, nhưng tên ví trong lịch sử sẽ hiển thị là \'Ví đã bị xóa\'.',
      'deleted_wallet_success': 'Đã xoá ví ',
      'close': 'Đóng',
      'add_new_wallet': 'Thêm ví mới',
      'new_group': 'Nhóm mới',
      'group_name': 'Tên nhóm',
      'expense_item': 'Khoản chi',
      'income_item': 'Khoản thu',
      'create_group': 'Tạo nhóm',
      'group_list': 'Danh sách nhóm',
      
      // Budgets
      'budgets': 'Ngân sách',
      'add_budget': 'Thêm ngân sách',
      'edit_budget': 'Sửa ngân sách',
      'remaining': 'Còn lại',
      'spent': 'Đã chi',
      'no_budgets': 'Bạn chưa có ngân sách nào',
      'budget_prompt_desc': 'Bắt đầu tiết kiệm bằng cách tạo ngân sách và chúng tôi sẽ giúp bạn kiểm soát chi tiêu của mình',
      'create_budget': 'TẠO NGÂN SÁCH',
      'this_week': 'Tuần này',
      'this_month': 'Tháng này',
      'this_quarter': 'Quý này',
      'this_year': 'Năm này',
      'please_enter_budget_amount': 'Vui lòng nhập số tiền định mức',
      'repeat_periodically': 'Lặp lại theo kỳ',
      'create_budget_btn': 'Tạo ngân sách',
      'no_finished_budgets': 'Chưa có ngân sách nào kết thúc',
      'start_date': 'Ngày bắt đầu',
      'end_date': 'Ngày kết thúc',
      'this_period': 'này',
      'remaining_colon': 'Còn lại:',
      'overspent_colon': 'Bội chi:',
      'in_progress': 'ĐANG ÁP DỤNG',
      'finished': 'ĐÃ KẾT THÚC',
      
      // Profile
      'login_prompt': 'Hãy đăng nhập để quản lý tài khoản của bạn',
      'delete_all_data': 'Xoá toàn bộ dữ liệu',
      'create_test_data': 'Tạo dự liệu test',
      'set_reminder': 'Đặt nhắc nhở',
      'date': 'Ngày',
      'time': 'Giờ',
      
      // Auth
      'welcome_back': 'Chào mừng trở lại!',
      'login_to_manage': 'Đăng nhập để quản lý chi tiêu của bạn',
      'username_or_email': 'Tên đăng nhập hoặc Email',
      'please_enter_username_or_email': 'Vui lòng nhập tên đăng nhập hoặc email',
      'password': 'Mật khẩu',
      'please_enter_password': 'Vui lòng nhập mật khẩu',
      'skip_login': 'Bỏ qua đăng nhập',
      'no_account': 'Chưa có tài khoản? ',
      'register_now': 'Đăng ký ngay',
      'password_not_match': 'Mật khẩu xác nhận không khớp',
      'register_success': 'Đăng ký thành công! Đang chuyển về trang đăng nhập...',
      'register_account': 'Đăng ký tài khoản',
      'create_new_account': 'Tạo tài khoản mới',
      'fill_info_to_register': 'Điền thông tin bên dưới để đăng ký',
      'display_name': 'Tên hiển thị',
      'please_enter_display_name': 'Vui lòng nhập tên hiển thị',
      'email': 'Email',
      'please_enter_email': 'Vui lòng nhập email',
      'invalid_email': 'Email không hợp lệ',
      'username': 'Tên đăng nhập',
      'please_enter_username': 'Vui lòng nhập tên đăng nhập',
      'username_min_length': 'Tên đăng nhập phải có ít nhất 3 ký tự',
      'password_min_length': 'Mật khẩu phải có ít nhất 6 ký tự',
      'confirm_password': 'Xác nhận mật khẩu',
      'please_confirm_password': 'Vui lòng xác nhận mật khẩu',
      'register': 'Đăng ký',
      'already_have_account': 'Đã có tài khoản? ',
      
      // Export & Backup
      'export_backup': 'Xuất & Sao lưu dữ liệu',
      'export_data': 'Xuất dữ liệu',
      'export_excel': 'Xuất Excel (.xlsx)',
      'export_pdf': 'Xuất PDF',
      'export_csv': 'Xuất CSV',
      'backup_data': 'Sao lưu dữ liệu',
      'restore_data': 'Khôi phục dữ liệu',
      'backup_section': 'Sao lưu',
      'restore_confirm': 'Dữ liệu hiện tại sẽ bị thay thế. Bạn có chắc?',
      'restore_success': 'Khôi phục dữ liệu thành công',
      'restore_fail': 'Khôi phục thất bại',
      'export_success': 'Xuất file thành công',
      'export_fail': 'Xuất file thất bại',
      'backup_success': 'Sao lưu thành công',
      'no_transactions_to_export': 'Không có giao dịch nào để xuất',
      'transaction_report': 'Báo cáo giao dịch',
      'export_date': 'Ngày xuất',
      'total_income': 'Tổng thu nhập',
      'total_expense': 'Tổng chi tiêu',
      'serial_number': 'STT',
      'title': 'Tiêu đề',
      'type': 'Loại',
      'group': 'Nhóm',
      'wallet': 'Ví',
      'export_filter': 'Bộ lọc xuất',
      'filter_all': 'Tất cả',
      'filter_day': 'Theo ngày',
      'filter_month': 'Theo tháng',
      'filter_quarter': 'Theo kỳ (quý)',
      'filter_year': 'Theo năm',
      'filter_range': 'Khoảng thời gian',
      'select_range': 'Chọn thời gian',

      // Confirmations
      'confirm_delete': 'Xác nhận xoá?',
      'delete_all_confirm': 'Xác nhận xoá toàn bộ dữ liệu?',
      'edit_wallet': 'Sửa ví',

      // Security
      'security': 'Bảo mật',
      'link_phone': 'Liên kết số điện thoại',
      'phone_number': 'Số điện thoại',
      'pin_code': 'Mã PIN',
      'create_pin_code': 'Tạo mã PIN',
      'change_pin_code': 'Đổi mã PIN',
      'enter_pin': 'Nhập mã PIN',
      'pin_created': 'Tạo mã PIN thành công',
      'pin_changed': 'Đổi mã PIN thành công',
      'pin_removed': 'Đã xoá mã PIN',
      'incorrect_pin': 'Mã PIN không chính xác',
      'change_password': 'Thay đổi mật khẩu',
      'old_password': 'Mật khẩu cũ',
      'new_password': 'Mật khẩu mới',
      'password_changed': 'Đổi mật khẩu thành công',
      'remove_pin': 'Xoá mã PIN',
      'please_enter_phone': 'Vui lòng nhập số điện thoại',
      'phone_linked': 'Đã liên kết số điện thoại',
      'remove_phone': 'Xoá liên kết số điện thoại',
      'phone_removed': 'Đã xoá số điện thoại',
      'pin_required_desc': 'Bạn cần phải tạo mã PIN để thực hiện hành động này. Bạn có muốn tạo bây giờ không?',
      'create_pin_now': 'Tạo mã PIN ngay',

      // ChatBot
      'chatbot_welcome': 'Xin chào! 👋 Hãy bắt đầu thêm giao dịch của bạn tại đây nhé!',
      'chatbot_hint': 'bữa tối 100k, mua sắm 400k',
      'chatbot_success_expense': 'Tuyệt vời! Mình đã ghi lại khoản chi của bạn vào danh mục {group}. Cùng giữ thói quen tốt nhé! 💪',
      'chatbot_success_income': 'Tuyệt vời! Mình đã ghi lại khoản thu của bạn vào danh mục {group}. Cùng giữ thói quen tốt nhé! 💪',
      'chatbot_error_parse': 'Xin lỗi, đã xảy ra lỗi trong quá trình phân tích. Vui lòng thử lại.',
      'chatbot_error_understand': 'Mình chưa hiểu rõ ý bạn, bạn có thể nói lại một giao dịch cụ thể hơn được không? (Ví dụ: "Sáng nay uống cafe 50k")',
      'chatbot_title': 'Hôm nay bạn đã chi tiêu gì?',
      'chatbot': 'Trợ lý tài chính',
      'chatbot_subtitle': 'Hỏi đáp với AI',
      'chatbot_spending': 'Chi Tiêu',
      'chatbot_no_transaction': 'Không có giao dịch nào trong khoảng thời gian này 📭',
      'chatbot_summary': '📊 Tổng kết: {count} giao dịch\n',
      'chatbot_total_expense': '💸 Chi: {amount}\n',
      'chatbot_total_income': '💰 Thu: {amount}',
      'chatbot_recorded': 'Đã ghi nhận: ',
      'chatbot_expense_label': 'Chi phí',
      'chatbot_income_label': 'Thu nhập',
      'chatbot_transfer_fund': 'Di chuyển quỹ',
      'chatbot_recurring': 'Giao dịch định kỳ',

      // Reminders
      'payment_reminders': 'Nhắc nhở thanh toán',
      'no_reminders_yet': 'Chưa có nhắc nhở nào.',
      'add_reminder': 'Thêm Nhắc Nhở',
      'edit_reminder': 'Sửa Nhắc Nhở',
      'reminder_title_hint': 'Tiêu đề (VD: Tiền điện tháng 3)',
      'bill_type': 'Loại hoá đơn',
      'expected_amount': 'Số tiền dự kiến',
      'due_date_label': 'Hạn thanh toán',
      'remind_before_days': 'Nhắc trước (ngày)',
      'notification_time': 'Giờ thông báo (mặc định 08:00)',
      'additional_notes': 'Ghi chú thêm',
      'save_reminder': 'Lưu Nhắc Nhở',
      'type_electricity': 'Điện',
      'type_water': 'Nước',
      'type_internet': 'Internet',
      'type_rent': 'Tiền nhà',
      'type_other': 'Khác',
      'mark_as_paid': 'Đánh dấu đã thanh toán',
      'delete_reminder': 'Xóa nhắc nhở',
      'x_days': 'ngày',
      'tomorrow': 'Ngày mai',
      'reminder_hint': 'Nhấn + để thêm nhắc nhở mới',
      'search_reminder': 'Tìm kiếm nhắc nhở...',
      'scan_receipt_tip': 'Tip: Nhấn quét hóa đơn để nhập liệu nhanh',
      'sort_newest': 'Mới nhất',
      'sort_due_soon': 'Sắp đến hạn',
      'no_results_found': 'Không tìm thấy kết quả',
      'enter_title': 'Vui lòng nhập tiêu đề',
      'enter_amount': 'Vui lòng nhập số tiền',
      
      // OCR & Scanning
      'scan_receipt': 'Quét hóa đơn',
      'select_receipt_image': 'Chọn ảnh hóa đơn/biên lai',
      'camera': 'Chụp ảnh',
      'gallery': 'Thư viện',
      'scanning_receipt': 'Đang phân tích hóa đơn...',
      'scan_result': 'Kết quả quét',
      'category': 'Danh mục',
      'items': 'Danh sách mặt hàng',
      'use_result': 'Sử dụng kết quả này',

      // Loan Management
      'loan_management': 'Sổ nợ',
      'loan_subtitle': 'Vay & Cho vay',
      'loan_borrow': 'Đi vay',
      'loan_lend': 'Cho vay',
      'total_borrowed': 'Tổng nợ còn lại',
      'total_lent': 'Tổng cho vay còn lại',
      'loan_items': 'khoản',
      'search_person': 'Tìm theo người...',
      'loan_unpaid': 'Chưa trả',
      'loan_partial': 'Trả một phần',
      'loan_paid': 'Đã trả',
      'no_loans': 'Chưa có sổ nợ nào',
      'loan_paid_amount': 'Đã trả',
      'loan_remaining': 'Còn lại',
      'loan_overdue': 'Quá hạn!',
      'add_loan': 'Thêm sổ nợ',
      'edit_loan': 'Sửa sổ nợ',
      'loan_borrower': 'Người vay',
      'loan_creditor': 'Chủ nợ',
      'please_enter_person': 'Vui lòng nhập tên người',
      'loan_date': 'Ngày mượn',
      'loan_due_date': 'Hạn trả',
      'not_set': 'Chưa đặt',
      'loan_detail': 'Chi tiết sổ nợ',
      'status': 'Trạng thái',
      'loan_payment_history': 'Lịch sử trả nợ',
      'loan_add_payment': 'Ghi nhận trả nợ',
      'no_payments': 'Chưa có lịch sử trả nợ',
      'confirm_delete_loan': 'Bạn có chắc muốn xóa sổ nợ này?',
      'confirm_delete_payment': 'Xóa lần trả này?',
      'loan_borrow_hint': 'Nhấn + để thêm khoản vay mới',
      'loan_lend_hint': 'Nhấn + để thêm khoản cho vay',

      // Categories
      'sub_category': 'Danh mục con',
      'edit_group': 'Sửa danh mục',
      'category_type': 'Loại danh mục',
      'category_color': 'Màu sắc',
      'parent_category': 'Danh mục cha',
      'no_parent': 'Không có (danh mục gốc)',
      'please_fill_all': 'Vui lòng điền đầy đủ',
      'confirm_delete_group': 'Bạn có chắc muốn xóa danh mục này? Các giao dịch thuộc danh mục này sẽ không bị xóa.',
      'version': 'Phiên bản',

      // Notifications
      'notifications': 'Thông báo',
      'mark_all_read': 'Đánh dấu tất cả đã đọc',
      'unread': 'Chưa đọc',
      'bill': 'Hoá đơn',
      'debt': 'Khoản nợ',
      'no_notifications': 'Không có thông báo nào',
      'reminder_payment_title': 'Nhắc thanh toán hoá đơn',
      'reminder_payment_body': 'Đến hạn thanh toán {0} số tiền {1}',
      'debt_due_title': 'Khoản nợ đến hạn',
      'debt_payment_body': 'Bạn cần trả {0} cho {1}',
      'loan_due_title': 'Khoản cho vay đến hạn',
      'loan_collection_body': 'Đến hạn thu {0} từ {1}',
      'loan_created_borrow': 'Đã tạo khoản vay',
      'loan_created_borrow_body': 'Bạn đã vay {0} từ {1}',
      'loan_created_lend': 'Đã tạo khoản cho vay',
      'loan_created_lend_body': 'Bạn đã cho {0} vay {1}',
    }
  };

  String? get(String key) {
    if (_localizedValues.containsKey(languageCode) && _localizedValues[languageCode]!.containsKey(key)) {
      return _localizedValues[languageCode]![key];
    }
    // Fallback to Vietnamese if key not found in selected language
    if (_localizedValues['vi']!.containsKey(key)) {
      return _localizedValues['vi']![key];
    }
    return null;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<S> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'vi'].contains(locale.languageCode);

  @override
  Future<S> load(Locale locale) async {
    return S(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
